
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dreams` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model dreams
 * 
 */
export type dreamsModel = runtime.Types.Result.DefaultSelection<Prisma.$dreamsPayload>

export type AggregateDreams = {
  _count: DreamsCountAggregateOutputType | null
  _avg: DreamsAvgAggregateOutputType | null
  _sum: DreamsSumAggregateOutputType | null
  _min: DreamsMinAggregateOutputType | null
  _max: DreamsMaxAggregateOutputType | null
}

export type DreamsAvgAggregateOutputType = {
  id: number | null
}

export type DreamsSumAggregateOutputType = {
  id: number | null
}

export type DreamsMinAggregateOutputType = {
  id: number | null
  text: string | null
  created_at: Date | null
}

export type DreamsMaxAggregateOutputType = {
  id: number | null
  text: string | null
  created_at: Date | null
}

export type DreamsCountAggregateOutputType = {
  id: number
  text: number
  created_at: number
  _all: number
}


export type DreamsAvgAggregateInputType = {
  id?: true
}

export type DreamsSumAggregateInputType = {
  id?: true
}

export type DreamsMinAggregateInputType = {
  id?: true
  text?: true
  created_at?: true
}

export type DreamsMaxAggregateInputType = {
  id?: true
  text?: true
  created_at?: true
}

export type DreamsCountAggregateInputType = {
  id?: true
  text?: true
  created_at?: true
  _all?: true
}

export type DreamsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dreams to aggregate.
   */
  where?: Prisma.dreamsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dreams to fetch.
   */
  orderBy?: Prisma.dreamsOrderByWithRelationInput | Prisma.dreamsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dreamsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dreams
  **/
  _count?: true | DreamsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DreamsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DreamsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DreamsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DreamsMaxAggregateInputType
}

export type GetDreamsAggregateType<T extends DreamsAggregateArgs> = {
      [P in keyof T & keyof AggregateDreams]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDreams[P]>
    : Prisma.GetScalarType<T[P], AggregateDreams[P]>
}




export type dreamsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dreamsWhereInput
  orderBy?: Prisma.dreamsOrderByWithAggregationInput | Prisma.dreamsOrderByWithAggregationInput[]
  by: Prisma.DreamsScalarFieldEnum[] | Prisma.DreamsScalarFieldEnum
  having?: Prisma.dreamsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DreamsCountAggregateInputType | true
  _avg?: DreamsAvgAggregateInputType
  _sum?: DreamsSumAggregateInputType
  _min?: DreamsMinAggregateInputType
  _max?: DreamsMaxAggregateInputType
}

export type DreamsGroupByOutputType = {
  id: number
  text: string
  created_at: Date | null
  _count: DreamsCountAggregateOutputType | null
  _avg: DreamsAvgAggregateOutputType | null
  _sum: DreamsSumAggregateOutputType | null
  _min: DreamsMinAggregateOutputType | null
  _max: DreamsMaxAggregateOutputType | null
}

export type GetDreamsGroupByPayload<T extends dreamsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DreamsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DreamsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DreamsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DreamsGroupByOutputType[P]>
      }
    >
  >



export type dreamsWhereInput = {
  AND?: Prisma.dreamsWhereInput | Prisma.dreamsWhereInput[]
  OR?: Prisma.dreamsWhereInput[]
  NOT?: Prisma.dreamsWhereInput | Prisma.dreamsWhereInput[]
  id?: Prisma.IntFilter<"dreams"> | number
  text?: Prisma.StringFilter<"dreams"> | string
  created_at?: Prisma.DateTimeNullableFilter<"dreams"> | Date | string | null
}

export type dreamsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type dreamsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.dreamsWhereInput | Prisma.dreamsWhereInput[]
  OR?: Prisma.dreamsWhereInput[]
  NOT?: Prisma.dreamsWhereInput | Prisma.dreamsWhereInput[]
  text?: Prisma.StringFilter<"dreams"> | string
  created_at?: Prisma.DateTimeNullableFilter<"dreams"> | Date | string | null
}, "id">

export type dreamsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.dreamsCountOrderByAggregateInput
  _avg?: Prisma.dreamsAvgOrderByAggregateInput
  _max?: Prisma.dreamsMaxOrderByAggregateInput
  _min?: Prisma.dreamsMinOrderByAggregateInput
  _sum?: Prisma.dreamsSumOrderByAggregateInput
}

export type dreamsScalarWhereWithAggregatesInput = {
  AND?: Prisma.dreamsScalarWhereWithAggregatesInput | Prisma.dreamsScalarWhereWithAggregatesInput[]
  OR?: Prisma.dreamsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dreamsScalarWhereWithAggregatesInput | Prisma.dreamsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"dreams"> | number
  text?: Prisma.StringWithAggregatesFilter<"dreams"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"dreams"> | Date | string | null
}

export type dreamsCreateInput = {
  text: string
  created_at?: Date | string | null
}

export type dreamsUncheckedCreateInput = {
  id?: number
  text: string
  created_at?: Date | string | null
}

export type dreamsUpdateInput = {
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dreamsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dreamsCreateManyInput = {
  id?: number
  text: string
  created_at?: Date | string | null
}

export type dreamsUpdateManyMutationInput = {
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dreamsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dreamsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type dreamsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type dreamsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type dreamsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type dreamsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type dreamsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  created_at?: boolean
}, ExtArgs["result"]["dreams"]>

export type dreamsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  created_at?: boolean
}, ExtArgs["result"]["dreams"]>

export type dreamsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  created_at?: boolean
}, ExtArgs["result"]["dreams"]>

export type dreamsSelectScalar = {
  id?: boolean
  text?: boolean
  created_at?: boolean
}

export type dreamsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "text" | "created_at", ExtArgs["result"]["dreams"]>

export type $dreamsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dreams"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    text: string
    created_at: Date | null
  }, ExtArgs["result"]["dreams"]>
  composites: {}
}

export type dreamsGetPayload<S extends boolean | null | undefined | dreamsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dreamsPayload, S>

export type dreamsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dreamsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DreamsCountAggregateInputType | true
  }

export interface dreamsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dreams'], meta: { name: 'dreams' } }
  /**
   * Find zero or one Dreams that matches the filter.
   * @param {dreamsFindUniqueArgs} args - Arguments to find a Dreams
   * @example
   * // Get one Dreams
   * const dreams = await prisma.dreams.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dreamsFindUniqueArgs>(args: Prisma.SelectSubset<T, dreamsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dreams that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dreamsFindUniqueOrThrowArgs} args - Arguments to find a Dreams
   * @example
   * // Get one Dreams
   * const dreams = await prisma.dreams.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dreamsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dreamsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dreams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dreamsFindFirstArgs} args - Arguments to find a Dreams
   * @example
   * // Get one Dreams
   * const dreams = await prisma.dreams.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dreamsFindFirstArgs>(args?: Prisma.SelectSubset<T, dreamsFindFirstArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dreams that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dreamsFindFirstOrThrowArgs} args - Arguments to find a Dreams
   * @example
   * // Get one Dreams
   * const dreams = await prisma.dreams.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dreamsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dreamsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dreams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dreamsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dreams
   * const dreams = await prisma.dreams.findMany()
   * 
   * // Get first 10 Dreams
   * const dreams = await prisma.dreams.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dreamsWithIdOnly = await prisma.dreams.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends dreamsFindManyArgs>(args?: Prisma.SelectSubset<T, dreamsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dreams.
   * @param {dreamsCreateArgs} args - Arguments to create a Dreams.
   * @example
   * // Create one Dreams
   * const Dreams = await prisma.dreams.create({
   *   data: {
   *     // ... data to create a Dreams
   *   }
   * })
   * 
   */
  create<T extends dreamsCreateArgs>(args: Prisma.SelectSubset<T, dreamsCreateArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dreams.
   * @param {dreamsCreateManyArgs} args - Arguments to create many Dreams.
   * @example
   * // Create many Dreams
   * const dreams = await prisma.dreams.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dreamsCreateManyArgs>(args?: Prisma.SelectSubset<T, dreamsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dreams and returns the data saved in the database.
   * @param {dreamsCreateManyAndReturnArgs} args - Arguments to create many Dreams.
   * @example
   * // Create many Dreams
   * const dreams = await prisma.dreams.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dreams and only return the `id`
   * const dreamsWithIdOnly = await prisma.dreams.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends dreamsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, dreamsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dreams.
   * @param {dreamsDeleteArgs} args - Arguments to delete one Dreams.
   * @example
   * // Delete one Dreams
   * const Dreams = await prisma.dreams.delete({
   *   where: {
   *     // ... filter to delete one Dreams
   *   }
   * })
   * 
   */
  delete<T extends dreamsDeleteArgs>(args: Prisma.SelectSubset<T, dreamsDeleteArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dreams.
   * @param {dreamsUpdateArgs} args - Arguments to update one Dreams.
   * @example
   * // Update one Dreams
   * const dreams = await prisma.dreams.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dreamsUpdateArgs>(args: Prisma.SelectSubset<T, dreamsUpdateArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dreams.
   * @param {dreamsDeleteManyArgs} args - Arguments to filter Dreams to delete.
   * @example
   * // Delete a few Dreams
   * const { count } = await prisma.dreams.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dreamsDeleteManyArgs>(args?: Prisma.SelectSubset<T, dreamsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dreams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dreamsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dreams
   * const dreams = await prisma.dreams.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dreamsUpdateManyArgs>(args: Prisma.SelectSubset<T, dreamsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dreams and returns the data updated in the database.
   * @param {dreamsUpdateManyAndReturnArgs} args - Arguments to update many Dreams.
   * @example
   * // Update many Dreams
   * const dreams = await prisma.dreams.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dreams and only return the `id`
   * const dreamsWithIdOnly = await prisma.dreams.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends dreamsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, dreamsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dreams.
   * @param {dreamsUpsertArgs} args - Arguments to update or create a Dreams.
   * @example
   * // Update or create a Dreams
   * const dreams = await prisma.dreams.upsert({
   *   create: {
   *     // ... data to create a Dreams
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dreams we want to update
   *   }
   * })
   */
  upsert<T extends dreamsUpsertArgs>(args: Prisma.SelectSubset<T, dreamsUpsertArgs<ExtArgs>>): Prisma.Prisma__dreamsClient<runtime.Types.Result.GetResult<Prisma.$dreamsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dreams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dreamsCountArgs} args - Arguments to filter Dreams to count.
   * @example
   * // Count the number of Dreams
   * const count = await prisma.dreams.count({
   *   where: {
   *     // ... the filter for the Dreams we want to count
   *   }
   * })
  **/
  count<T extends dreamsCountArgs>(
    args?: Prisma.Subset<T, dreamsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DreamsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dreams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DreamsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DreamsAggregateArgs>(args: Prisma.Subset<T, DreamsAggregateArgs>): Prisma.PrismaPromise<GetDreamsAggregateType<T>>

  /**
   * Group by Dreams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dreamsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dreamsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dreamsGroupByArgs['orderBy'] }
      : { orderBy?: dreamsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dreamsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDreamsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dreams model
 */
readonly fields: dreamsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dreams.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dreamsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dreams model
 */
export interface dreamsFieldRefs {
  readonly id: Prisma.FieldRef<"dreams", 'Int'>
  readonly text: Prisma.FieldRef<"dreams", 'String'>
  readonly created_at: Prisma.FieldRef<"dreams", 'DateTime'>
}
    

// Custom InputTypes
/**
 * dreams findUnique
 */
export type dreamsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * Filter, which dreams to fetch.
   */
  where: Prisma.dreamsWhereUniqueInput
}

/**
 * dreams findUniqueOrThrow
 */
export type dreamsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * Filter, which dreams to fetch.
   */
  where: Prisma.dreamsWhereUniqueInput
}

/**
 * dreams findFirst
 */
export type dreamsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * Filter, which dreams to fetch.
   */
  where?: Prisma.dreamsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dreams to fetch.
   */
  orderBy?: Prisma.dreamsOrderByWithRelationInput | Prisma.dreamsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dreams.
   */
  cursor?: Prisma.dreamsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dreams.
   */
  distinct?: Prisma.DreamsScalarFieldEnum | Prisma.DreamsScalarFieldEnum[]
}

/**
 * dreams findFirstOrThrow
 */
export type dreamsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * Filter, which dreams to fetch.
   */
  where?: Prisma.dreamsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dreams to fetch.
   */
  orderBy?: Prisma.dreamsOrderByWithRelationInput | Prisma.dreamsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dreams.
   */
  cursor?: Prisma.dreamsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dreams.
   */
  distinct?: Prisma.DreamsScalarFieldEnum | Prisma.DreamsScalarFieldEnum[]
}

/**
 * dreams findMany
 */
export type dreamsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * Filter, which dreams to fetch.
   */
  where?: Prisma.dreamsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dreams to fetch.
   */
  orderBy?: Prisma.dreamsOrderByWithRelationInput | Prisma.dreamsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dreams.
   */
  cursor?: Prisma.dreamsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dreams.
   */
  distinct?: Prisma.DreamsScalarFieldEnum | Prisma.DreamsScalarFieldEnum[]
}

/**
 * dreams create
 */
export type dreamsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * The data needed to create a dreams.
   */
  data: Prisma.XOR<Prisma.dreamsCreateInput, Prisma.dreamsUncheckedCreateInput>
}

/**
 * dreams createMany
 */
export type dreamsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dreams.
   */
  data: Prisma.dreamsCreateManyInput | Prisma.dreamsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dreams createManyAndReturn
 */
export type dreamsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * The data used to create many dreams.
   */
  data: Prisma.dreamsCreateManyInput | Prisma.dreamsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dreams update
 */
export type dreamsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * The data needed to update a dreams.
   */
  data: Prisma.XOR<Prisma.dreamsUpdateInput, Prisma.dreamsUncheckedUpdateInput>
  /**
   * Choose, which dreams to update.
   */
  where: Prisma.dreamsWhereUniqueInput
}

/**
 * dreams updateMany
 */
export type dreamsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dreams.
   */
  data: Prisma.XOR<Prisma.dreamsUpdateManyMutationInput, Prisma.dreamsUncheckedUpdateManyInput>
  /**
   * Filter which dreams to update
   */
  where?: Prisma.dreamsWhereInput
  /**
   * Limit how many dreams to update.
   */
  limit?: number
}

/**
 * dreams updateManyAndReturn
 */
export type dreamsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * The data used to update dreams.
   */
  data: Prisma.XOR<Prisma.dreamsUpdateManyMutationInput, Prisma.dreamsUncheckedUpdateManyInput>
  /**
   * Filter which dreams to update
   */
  where?: Prisma.dreamsWhereInput
  /**
   * Limit how many dreams to update.
   */
  limit?: number
}

/**
 * dreams upsert
 */
export type dreamsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * The filter to search for the dreams to update in case it exists.
   */
  where: Prisma.dreamsWhereUniqueInput
  /**
   * In case the dreams found by the `where` argument doesn't exist, create a new dreams with this data.
   */
  create: Prisma.XOR<Prisma.dreamsCreateInput, Prisma.dreamsUncheckedCreateInput>
  /**
   * In case the dreams was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dreamsUpdateInput, Prisma.dreamsUncheckedUpdateInput>
}

/**
 * dreams delete
 */
export type dreamsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
  /**
   * Filter which dreams to delete.
   */
  where: Prisma.dreamsWhereUniqueInput
}

/**
 * dreams deleteMany
 */
export type dreamsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dreams to delete
   */
  where?: Prisma.dreamsWhereInput
  /**
   * Limit how many dreams to delete.
   */
  limit?: number
}

/**
 * dreams without action
 */
export type dreamsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dreams
   */
  select?: Prisma.dreamsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dreams
   */
  omit?: Prisma.dreamsOmit<ExtArgs> | null
}
